export const SAINTS_CALENDAR: Record<number, Record<number, string[]>> = {
  1: { // Janeiro
    1: ["Solenidade de Maria Mãe de Deus", "São Fulgêncio"],
    2: ["São Basílio Magno e Gregório Nazianzo"],
    3: ["Santa Genoveva", "São Tito"],
    4: ["Santa Ângela de Folinho"],
    5: ["São João Neumann"],
    6: ["Epifania do Senhor (Reis Magos)"],
    7: ["São Raimundo de Peñafort"],
    8: ["São Severino"],
    9: ["Santo André Corsini"],
    10: ["Frei Gonçalo de Amarante"],
    11: ["Santo Higino"],
    12: ["São Bernardo de Corleone"],
    13: ["São Hilário de Poitiers"],
    14: ["Santa Elisabete Ana Seton"],
    15: ["Santo Amaro"],
    16: ["Santo Honorato"],
    17: ["Santo Antão Abade", "Santa Rosa de Viterbo"],
    18: ["Santa Margarida da Hungria"],
    19: ["São Canuto"],
    20: ["São Fabião e São Sebastião"],
    21: ["Santa Inês"],
    22: ["São Vicente Diácono"],
    23: ["Santo Ildefonso"],
    24: ["São Francisco de Sales"],
    25: ["Conversão de São Paulo Apóstolo"],
    26: ["Santos Timóteo e Tito"],
    27: ["Santa Ângela Mérici"],
    28: ["Santo Tomás de Aquino"],
    29: ["Beata Lindalva Justo de Oliveira"],
    31: ["São João Bosco (Dom Bosco)"]
  },
  2: { // Fevereiro
    1: ["São Henrique de Cochinchina"],
    2: ["Apresentação do Senhor"],
    3: ["São Brás", "São Óscar (Ansgar)"],
    4: ["São Gilberto"],
    5: ["Santa Águeda (Ágata)"],
    6: ["Santos Paulo Miki e Companheiros Mártires"],
    8: ["São Jerônimo Emiliani", "Santa Josefina Bakhita"],
    9: ["Santa Apolônia"],
    10: ["Santa Escolástica"],
    11: ["Nossa Senhora de Lourdes"],
    14: ["Santos Cirilo e Metódio", "São Valentim"],
    17: ["Sete Fundadores da Ordem dos Servitas"],
    18: ["São Simeão"],
    21: ["São Pedro Damião"],
    22: ["Cátedra de São Pedro Apóstolo"],
    23: ["São Policarpo"],
    27: ["São Gabriel da Virgem das Dores"],
    28: ["São Romão"]
  },
  3: { // Março
    1: ["São Albino"],
    3: ["Santa Cunegunda"],
    4: ["São Casimiro"],
    7: ["Santos Perpétua e Felicidade"],
    8: ["São João de Deus"],
    9: ["Santa Francisca Romana"],
    10: ["São João Ogilvie"],
    12: ["São Gregório Magno"],
    13: ["Santo Rodrigo"],
    17: ["São Patrício"],
    18: ["São Cirilo de Jerusalém"],
    19: ["São José, Esposo de Maria"],
    23: ["São Turíbio de Mongrovejo"],
    25: ["Anunciação do Senhor"],
    27: ["São Ruperto"],
    30: ["São Leonardo Murialdo"]
  },
  4: { // Abril
    2: ["São Francisco de Paula"],
    3: ["São Ricardo"],
    4: ["São Isidoro de Sevilha"],
    5: ["São Vicente Ferrer"],
    7: ["São João Batista de la Salle"],
    11: ["São Estanislau de Cracóvia"],
    13: ["São Martim I"],
    14: ["São Maximino"],
    17: ["Santa Inês de Montepulciano"],
    19: ["Santo Expedito"],
    21: ["Santo Anselmo", "São Conrado de Parzham"],
    22: ["São Sotero e Caio"],
    23: ["São Jorge Mártir"],
    24: ["São Fidélis de Sigmaringen"],
    25: ["São Marcos Evangelista"],
    26: ["Nossa Senhora do Bom Conselho"],
    27: ["São Pedro Canísio"],
    28: ["São Pedro Chanel", "São Luís Maria Grignon de Montfort"],
    29: ["Santa Catarina de Sena"],
    30: ["São Pio V"]
  },
  5: { // Maio
    1: ["São José Operário"],
    2: ["São Atanásio"],
    3: ["Santos Filipe e Tiago Apóstolos"],
    4: ["São Peregrino"],
    7: ["São Domingos Sávio"],
    10: ["São João de Ávila"],
    12: ["Santos Néreo e Aquileu", "São Pancrácio"],
    13: ["Nossa Senhora de Fátima", "São Pedro Regalado"],
    14: ["São Matias Apóstolo"],
    15: ["São Isidoro Lavrador"],
    16: ["São Simão Stock", "Santa Margarida de Cortona"],
    17: ["São Pascoal Bailão"],
    18: ["São João I", "São Félix de Cantalice"],
    19: ["São Ivo"],
    20: ["São Bernardino de Sena"],
    21: ["São Cristóvão Magalhães (Mártir do Brasil)"],
    22: ["Santa Rita de Cássia"],
    23: ["Santa Rosa de Lima"],
    24: ["Nossa Senhora Auxiliadora"],
    25: ["São Gregório VII", "Santa Maria Madalena de Pazzi", "São Beda Venerável"],
    26: ["São Filipe Néri"],
    27: ["Santo Agostinho de Cantuária"],
    31: ["Visitação de Nossa Senhora"]
  },
  6: { // Junho
    1: ["São Justino Mártir"],
    2: ["Santos Marcelino e Pedro"],
    3: ["Carlos Lwanga e Companheiros Mártires"],
    5: ["São Bonifácio"],
    6: ["São Norberto"],
    9: ["São Columbano"],
    10: ["Beato Nuno de Santa Maria"],
    11: ["São Barnabé Apóstolo"],
    13: ["Santo Antônio de Pádua"],
    19: ["São Romualdo"],
    20: ["São Silverio"],
    21: ["São Luís Gonzaga"],
    22: ["São João Fisher e São Tomás More"],
    24: ["Natividade de São João Batista"],
    27: ["São Cirilo de Alexandria"],
    28: ["São Irineu de Lyon"],
    29: ["São Pedro e São Paulo Apóstolos"],
    30: ["Primeiros Mártires de Roma"]
  },
  7: { // Julho
    1: ["São Aarão"],
    3: ["São Tomé Apóstolo"],
    4: ["Santa Isabel de Portugal"],
    5: ["Santo Antônio Maria Zaccaria"],
    6: ["Santa Maria Goretti"],
    8: ["Santo Agostinho Zhao Rong e Companheiros"],
    9: ["Santos Nicolau Pick e Companheiros Mártires"],
    11: ["São Bento Abade"],
    13: ["São Henrique II"],
    14: ["São Francisco Solano", "São Camilo de Lellis"],
    15: ["São Boaventura"],
    16: ["Nossa Senhora do Carmo"],
    17: ["Beato Inácio de Azevedo e Companheiros"],
    20: ["Santa Margarida de Antioquia"],
    21: ["São Lourenço de Brindisi"],
    22: ["Santa Maria Madalena"],
    23: ["Santa Brígida da Suécia"],
    24: ["São Charbel Makhlouf"],
    25: ["São Tiago Apóstolo Maior"],
    26: ["Santos Joaquim e Ana"],
    27: ["São Pantaleão"],
    29: ["Santa Marta", "São Lázaro"],
    30: ["São Pedro Crisólogo"],
    31: ["Santo Inácio de Loyola"]
  },
  8: { // Agosto
    1: ["Santo Afonso Maria de Ligório"],
    2: ["São Eusébio de Vercelli", "São Pedro Julião Eymard"],
    4: ["São João Maria Vianney (Cura d'Ars)"],
    5: ["Dedicação da Basílica de Santa Maria Maior"],
    6: ["Transfiguração do Senhor"],
    7: ["São Sixto II e Companheiros", "São Caetano"],
    8: ["São Domingos de Gusmão"],
    9: ["Santa Teresa Benedita da Cruz (Edith Stein)"],
    10: ["São Lourenço Diácono e Mártir"],
    11: ["Santa Clara de Assis"],
    12: ["Santa Joana Francisca de Chantal"],
    13: ["Santos Hipólito e Cassiano"],
    14: ["São Maximiliano Maria Kolbe"],
    15: ["Assunção de Nossa Senhora (Solenidade)"],
    16: ["São Estevão da Hungria", "São Roque"],
    17: ["São Jacinto"],
    18: ["Santa Helena"],
    19: ["São João Eudes"],
    20: ["São Bernardo de Claraval"],
    21: ["São Pio X"],
    22: ["Nossa Senhora Rainha"],
    23: ["Santa Rosa de Lima"],
    24: ["São Bartolomeu Apóstolo"],
    25: ["São Luís IX, Rei da França", "São José de Calasanz"],
    27: ["Santa Mônica"],
    28: ["Santo Agostinho de Hipona"],
    29: ["Martírio de São João Batista"]
  },
  9: { // Setembro
    1: ["São Egídio"],
    3: ["São Gregório Magno"],
    5: ["Santa Tereza de Calcutá"],
    8: ["Natividade de Nossa Senhora"],
    9: ["São Pedro Claver"],
    12: ["Santíssimo Nome de Maria"],
    13: ["São João Crisóstomo"],
    14: ["Exaltação da Santa Cruz"],
    15: ["Nossa Senhora das Dores"],
    16: ["Santos Cornélio e Cipriano"],
    17: ["São Roberto Bellarmino", "São Lamberto"],
    19: ["São Januário"],
    20: ["Santos André de Soveral, Ambrósio Ferro e Mártires do Brasil"],
    21: ["São Mateus Apóstolo e Evangelista"],
    22: ["São Maurício"],
    23: ["São Pio de Pietrelcina (Padre Pio)"],
    24: ["Nossa Senhora das Mercês"],
    26: ["Santos Cosme e Damião"],
    27: ["São Vicente de Paulo"],
    28: ["São Lourenço Ruiz e Companheiros"],
    29: ["Santos Miguel, Gabriel e Rafael Arcanjos"],
    30: ["São Jerônimo"]
  },
  10: { // Outubro
    1: ["Santa Teresa do Menino Jesus"],
    2: ["Santos Anjos da Guarda"],
    3: ["São Francisco Borja"],
    4: ["São Francisco de Assis"],
    5: ["São Fausto"],
    6: ["São Bruno"],
    7: ["Nossa Senhora do Rosário"],
    9: ["São Dionísio e Companheiros", "São João Leonardi"],
    11: ["São João XXIII"],
    13: ["São Eduardo"],
    14: ["São Calisto I"],
    15: ["Santa Teresa de Ávila"],
    16: ["Santa Margarida Maria Alacoque", "Santa Edviges"],
    17: ["São Inácio de Antioquia"],
    18: ["São Lucas Evangelista"],
    19: ["São Paulo da Cruz", "São João de Brébeuf"],
    21: ["Santa Úrsula"],
    22: ["São João Paulo II"],
    23: ["São João Capistrano"],
    24: ["São Antônio Maria Claret"],
    28: ["Santos Simão e Judas Apóstolos"],
    31: ["São Quintino"]
  },
  11: { // Novembro
    1: ["Todos os Santos (Solenidade)"],
    2: ["Comemoração de Todos os Fiéis Defuntos"],
    3: ["São Martinho de Porres (Lima)"],
    4: ["São Carlos Borromeu"],
    5: ["São Zacarias e Santa Isabel"],
    6: ["São Leonardo de Noblac"],
    9: ["Dedicação da Basílica de Latrão"],
    10: ["São Leão Magno"],
    11: ["São Martinho de Tours"],
    12: ["São Josafá"],
    13: ["São Estanislau Kostka"],
    15: ["São Alberto Magno"],
    16: ["Santa Gertrudis", "Santa Margarida da Escócia"],
    17: ["Santa Isabel da Hungria"],
    18: ["Dedicação das Basílicas de Pedro e Paulo"],
    21: ["Apresentação de Nossa Senhora"],
    22: ["Santa Cecília"],
    23: ["São Clemente I", "São Columbano"],
    24: ["Santos André Dung-Lac e Companheiros"],
    25: ["Santa Catarina de Alexandria"],
    30: ["São André Apóstolo"]
  },
  12: { // Dezembro
    1: ["São Elói"],
    2: ["Santa Bibiana"],
    3: ["São Francisco Xavier"],
    4: ["São João Damasceno"],
    6: ["São Nicolau"],
    7: ["São Ambrósio"],
    8: ["Imaculada Conceição de Maria (Solenidade)"],
    9: ["São Pedro Fourier", "Beato Juan Diego"],
    10: ["Nossa Senhora de Loreto"],
    11: ["São Dâmaso I"],
    12: ["Nossa Senhora de Guadalupe"],
    13: ["Santa Luzia"],
    14: ["São João da Cruz"],
    21: ["São Pedro Canísio"],
    23: ["São João Cancio"],
    25: ["Natividade do Senhor – Natal (Solenidade)"],
    26: ["São Estevão Proto-Mártir"],
    27: ["São João Apóstolo e Evangelista"],
    28: ["Santos Inocentes Mártires"],
    29: ["São Tomás Becket"],
    31: ["São Silvestre I"]
  }
};

export function getSaintOfToday(): string {
  // Obtém data no fuso de Brasília (UTC-3)
  const now = new Date();
  const brtOffset = -3 * 60; // em minutos
  const brtDate = new Date(now.getTime() + (brtOffset + now.getTimezoneOffset()) * 60000);
  
  const month = brtDate.getMonth() + 1;
  const day = brtDate.getDate();

  const saints = SAINTS_CALENDAR[month]?.[day];
  
  if (!saints || saints.length === 0) {
    return "Santo do Dia";
  }

  // Se for apenas um, retorna ele.
  if (saints.length === 1) return saints[0];
  
  // Se forem vários, junta com " e " no final
  const allButLast = saints.slice(0, -1).join(", ");
  const last = saints[saints.length - 1];
  return `${allButLast} e ${last}`;
}
